fisco_bcos_toolbox/user/views.py
# -*- coding: utf-8 -*-
"""User views."""
from flask import Blueprint, render_template
from flask_login import login_required
from fb_python_sdk.client_config import client_config

blueprint = Blueprint("user", __name__, url_prefix="/users", static_folder="../static")


@blueprint.route("/")
@login_required
def members():
    """List members."""
    return render_template("users/members.html")

@blueprint.route("/sdk_config")
@login_required
def sdk_config():
    """List members."""
    # TODO handle url and posts
    return render_template("users/sdk_config.html", client_config=client_config)

fisco_bcos_toolbox/templates/footer.html
<footer>
  <small>
  <ul class="company">
    <li><a target="_blank" href="https://suibe.net">© SUIBE</a></li>
  </ul>

    <ul class="footer-nav">

      <li><a href="{{ url_for('public.about') }}">About</a></li>

      <li><a href="mailto:leeduckgo@gmail.com">Contact</a></li>
    </ul>
    <p>
      <small>
          {% if current_user.is_authenticated %}
              <a href="{{ url_for('public.logout', next=request.full_path) }}">Logout</a>
      |        <a href="{{ url_for('public.register', next=request.full_path)}}">Register</a>
          {% else %}
              <a href="{{ url_for('public.login', next=request.full_path) }}">Login</a>
      |        <a href="{{ url_for('public.register', next=request.full_path)}}">Register</a>
          {% endif %}
      </small>
  </p>
  </small>
</footer>

fisco_bcos_toolbox/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="{{ url_for('public.home') }}">
     FISCO BCOS Toolbox 
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
    aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{{ url_for('public.home') }}">主页
          <span class="sr-only">(current)</span>
        </a>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown">配置</a>
        <ul class="dropdown-menu" role="menu">
          <li class="nav-item"><a href="{{ url_for('public.sdk_config') }}">SDK配置</a></li>
          <li class="nav-item"><a href="{{ url_for('public.about') }}">节点配置</a></li>
        </ul>
      </li>
      {% if current_user and current_user.is_authenticated %}
<!--       
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('user.sdk_config') }}">配置 SDK</a>
        
      </li> -->
    
      {% endif %}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown">区块链开发学习</a>
        <ul class="dropdown-menu" role="menu">
          <li class="nav-item">
            <a href="https://learnblockchain.cn/column/2" target="_blank">联盟链开发</a>
          </li>
        </ul>
      </li>
      
      <li class="nav-item">
        <a class="nav-link" href="https://wetty.cnmf.net.cn/wetty" target="_blank">多链虚拟控制台</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown">我的数字身份</a>
        <ul class="dropdown-menu" role="menu">
          <li class="nav-item"><a href="{{ url_for('public.sdk_config') }}">身份</a></li>
          <li class="nav-item"><a href="{{ url_for('public.about') }}">证书</a></li>
          <li class="nav-item"><a href="{{ url_for('public.about') }}">链上数据</a></li>
          <li class="nav-item"><a href="{{ url_for('public.about') }}">数据共享</a></li>
        </ul>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('public.about') }}">关于</a>
      </li>



    </ul>

    {% if current_user and current_user.is_authenticated %}
    <ul class="navbar-nav my-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{{ url_for('user.members') }}">Logged in as {{ current_user.username }}</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('public.logout') }}">
          <i class="fa fa-sign-out"></i>
        </a>
      </li>
    </ul>
    {% elif form %}
   <form class="form-inline" id="loginForm" method="POST" action="/" role="login">
      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
      <div class="input-group mb-2 mr-sm-2">
        {{ form.username(placeholder="Username", class_="form-control mr-sm-1 my-auto") }} {{ form.password(placeholder="Password",
        class_="form-control mr-sm-1 my-auto") }}
        <button class="btn btn-light btn-primary m-auto" type="submit">Login</button>
      </div>
    </form>
    <ul class="navbar-nav my-auto">
      <li class="nav-item">
        <a class="nav-link navbar-text" href="{{ url_for('public.register') }}">Create account</a>
      </li>
    </ul>
    {% endif %}
  </div><!-- /.navbar-collapse -->
</nav>